In [1]:
import pandas as pd

In [2]:
exchange = pd.read_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Raw Data\Exchange rate USDPKR (2010-2026).csv"
)

In [3]:
exchange.head()

,Dataset Name,Observation Date,Series Key,Series Display Name,Observation Value,Unit,Observation Status,Observation Status Comment,Sequence No.,Series name
0,Bank Floating Average Exchange Rates (PKR per...,30-Jun-2026,TS_GP_ER_FAERPKR_M.E00010,1 Average Exchange rate of Pak Rupees per Aust...,196.153556,PKR,Normal,NaN,10,Average Exchange rate of Pak Rupees per Austra...
1,Bank Floating Average Exchange Rates (PKR per...,30-Jun-2026,TS_GP_ER_FAERPKR_M.E00020,2 Average Exchange rate of Pak Rupees per Bahr...,737.754818,PKR,Normal,NaN,20,Average Exchange rate of Pak Rupees per Bahrai...
2,Bank Floating Average Exchange Rates (PKR per...,30-Jun-2026,TS_GP_ER_FAERPKR_M.E00030,3 Average Exchange rate of Pak Rupees per Cana...,198.977795,PKR,Normal,NaN,30,Average Exchange rate of Pak Rupees per Canadi...
3,Bank Floating Average Exchange Rates (PKR per...,30-Jun-2026,TS_GP_ER_FAERPKR_M.E00040,4 Average Exchange rate of Pak Rupees per Chin...,41.130347,PKR,Normal,NaN,40,Average Exchange rate of Pak Rupees per Chines...
4,Bank Floating Average Exchange Rates (PKR per...,30-Jun-2026,TS_GP_ER_FAERPKR_M.E00050,5 Average Exchange rate of Pak Rupees per Dani...,43.012964,PKR,Normal,NaN,50,Average Exchange rate of Pak Rupees per Danish...

In [4]:
exchange.shape

(9504, 10)

In [5]:
exchange.columns

Index(['Dataset Name', 'Observation Date', 'Series Key', 'Series Display Name',
       'Observation Value', 'Unit', 'Observation Status',
       'Observation Status Comment', 'Sequence No.', 'Series name'],
      dtype='object')

In [6]:
exchange.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9504 entries, 0 to 9503
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Dataset Name                9504 non-null   object
 1   Observation Date            9504 non-null   object
 2   Series Key                  9504 non-null   object
 3   Series Display Name         9504 non-null   object
 4   Observation Value           9504 non-null   float64
 5   Unit                        9504 non-null   object
 6   Observation Status          9504 non-null   object
 7   Observation Status Comment  0 non-null      float64
 8   Sequence No.                9504 non-null   int64
 9   Series name                 9504 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 742.6+ KB

In [7]:
exchange.isnull().sum()

Dataset Name                     0
Observation Date                 0
Series Key                       0
Series Display Name              0
Observation Value                0
Unit                             0
Observation Status               0
Observation Status Comment    9504
Sequence No.                     0
Series name                      0
dtype: int64

In [8]:
exchange.duplicated().sum()

np.int64(0)

In [9]:
exchange["Series name"].unique()

array(['Average Exchange rate of Pak Rupees per Australian Dollar',
       'Average Exchange rate of Pak Rupees per Bahraini Dinar',
       'Average Exchange rate of Pak Rupees per Canadian Dollar',
       'Average Exchange rate of Pak Rupees per Chinese Yuan',
       'Average Exchange rate of Pak Rupees per Danish Krone',
       'Average Exchange rate of Pak Rupees per Hong Kong Dollar',
       'Average Exchange rate of Pak Rupees per Japanese Yen',
       'Average Exchange rate of Pak Rupees per Kuwaiti Dinar',
       'Average Exchange rate of Pak Rupees per Malaysian Ringgit',
       'Average Exchange rate of Pak Rupees per New Zealand Dollar',
       'Average Exchange rate of Pak Rupees per Norwegian Krone',
       'Average Exchange rate of Pak Rupees per Omani Rial',
       'Average Exchange rate of Pak Rupees per Qatari Rial',
       'Average Exchange rate of Pak Rupees per Singaporean Dollar',
       'Average Exchange rate of Pak Rupees per Swedish Krone',
       'Average Exchange rate of Pak Rupees per Swiss Franc',
       'Average Exchange rate of Pak Rupees per Saudi Arabian Rial',
       'Average Exchange rate of Pak Rupees per Thai Baht',
       'Average Exchange rate of Pak Rupees per Turkish Lira',
       'Average Exchange rate of Pak Rupees per UAE Dirham',
       'Average Exchange rate of Pak Rupees per UK Pound Sterling',
       'Average Exchange rate of Pak Rupees per U.S. Dollar',
       'Average Exchange rate of Pak Rupees per Euro',
       'Average Exchange rate of Pak Rupees per  SDR',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Australian Dollar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Bahraini Dinar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Canadian Dollar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Chinese Yuan',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Danish Krone',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Hong Kong Dollar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Japanese Yen',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Kuwaiti Dinar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Malaysian Ringgit',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per New Zealand Dollar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Norwegian Krone',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Omani Rial',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Qatari Rial',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Singaporean Dollar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Swedish Krone',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Swiss Franc',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Saudi Arabian Rial',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Thai Baht',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Turkish Lira',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per UAE Dirham',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per UK Pound Sterling',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per U.S. Dollar',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per Euro',
       'App (+) / Dep (-) Average Exchange rate of Pak Rupees per  SDR'],
      dtype=object)

In [10]:
exchange_filtered = exchange[
    exchange["Series name"] == "Average Exchange rate of Pak Rupees per U.S. Dollar"
]

In [11]:
exchange_filtered.shape

(198, 10)

In [12]:
exchange_clean = exchange_filtered[
    ["Observation Date", "Observation Value"]
].copy()

In [13]:
exchange_clean.columns = [
    "Date",
    "USD_PKR"
]

In [14]:
exchange_clean.columns

Index(['Date', 'USD_PKR'], dtype='object')

In [15]:
exchange_clean["Date"] = pd.to_datetime(
    exchange_clean["Date"],
    format="%d-%b-%Y"
)

In [16]:
exchange_clean = exchange_clean.sort_values("Date")

In [17]:
exchange_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 198 entries, 9477 to 21
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     198 non-null    datetime64[ns]
 1   USD_PKR  198 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.6 KB

In [18]:
exchange_clean.head()

           Date    USD_PKR
9477 2010-01-31  84.518436
9429 2010-02-28  84.899116
9381 2010-03-31  84.350006
9333 2010-04-30  83.938573
9285 2010-05-31  84.331786

In [19]:
exchange_clean.tail()

          Date     USD_PKR
213 2026-02-28  279.807007
165 2026-03-31  279.511286
117 2026-04-30  279.175974
69  2026-05-31  278.844538
21  2026-06-30  278.579554

In [20]:
exchange_clean["Date"].duplicated().sum()

np.int64(0)

In [21]:
exchange_clean.to_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Cleaned Data\Exchange_Rate_Cleaned.csv",
    index=False
)