In [1]:
import pandas as pd

In [2]:
remittances = pd.read_csv(r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Raw Data\Remittances (2005-2026).csv")

In [3]:
remittances.head()

,Dataset,Series Key,Series,Observation Date,Observation Value,Unit,Observation Status,Observation Status Comment
0,Seasonally Adjusted Workers’ Remittances,TS_GP_ES_SWR_M.SWR0002,Seasonally Adjusted WR (SWR),30-Jun-2026,3210.32,Million USD,Normal,NaN
1,Seasonally Adjusted Workers’ Remittances,TS_GP_ES_SWR_M.SWR0002,Seasonally Adjusted WR (SWR),31-May-2026,4016.52,Million USD,Normal,NaN
2,Seasonally Adjusted Workers’ Remittances,TS_GP_ES_SWR_M.SWR0002,Seasonally Adjusted WR (SWR),30-Apr-2026,3500.57,Million USD,Normal,NaN
3,Seasonally Adjusted Workers’ Remittances,TS_GP_ES_SWR_M.SWR0002,Seasonally Adjusted WR (SWR),31-Mar-2026,3591.73,Million USD,Normal,NaN
4,Seasonally Adjusted Workers’ Remittances,TS_GP_ES_SWR_M.SWR0002,Seasonally Adjusted WR (SWR),28-Feb-2026,3705.15,Million USD,Normal,NaN

In [4]:
remittances.shape

(252, 8)

In [5]:
remittances.columns

Index(['Dataset', 'Series Key', 'Series', 'Observation Date',
       'Observation Value', 'Unit', 'Observation Status',
       'Observation Status Comment'],
      dtype='object')

In [6]:
remittances.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Dataset                     252 non-null    object
 1   Series Key                  252 non-null    object
 2   Series                      252 non-null    object
 3   Observation Date            252 non-null    object
 4   Observation Value           252 non-null    float64
 5   Unit                        252 non-null    object
 6   Observation Status          252 non-null    object
 7   Observation Status Comment  0 non-null      float64
dtypes: float64(2), object(6)
memory usage: 15.9+ KB

In [7]:
remittances.isnull().sum()

Dataset                         0
Series Key                      0
Series                          0
Observation Date                0
Observation Value               0
Unit                            0
Observation Status              0
Observation Status Comment    252
dtype: int64

In [8]:
remittances.duplicated().sum()

np.int64(0)

In [9]:
remittances["Series"].unique()

array(['Seasonally Adjusted WR (SWR)'], dtype=object)

In [10]:
remittances_clean = remittances[
    ["Observation Date", "Observation Value"]
].copy()

In [11]:
remittances_clean.columns = ["Date", "Remittances_Million_USD"]

In [12]:
remittances_clean["Date"] = pd.to_datetime(
    remittances_clean["Date"],
    format="%d-%b-%Y"
)

In [13]:
remittances_clean = remittances_clean.sort_values("Date")

In [14]:
remittances_clean.head()

          Date  Remittances_Million_USD
251 2005-07-31                   320.67
250 2005-08-31                   341.07
249 2005-09-30                   347.82
248 2005-10-31                   328.54
247 2005-11-30                   355.79

In [15]:
remittances_clean.tail()

        Date  Remittances_Million_USD
4 2026-02-28                  3705.15
3 2026-03-31                  3591.73
2 2026-04-30                  3500.57
1 2026-05-31                  4016.52
0 2026-06-30                  3210.32

In [16]:
remittances_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 252 entries, 251 to 0
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     252 non-null    datetime64[ns]
 1   Remittances_Million_USD  252 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 5.9 KB

In [19]:
remittances = remittances[
    remittances["Observation Date"] >= "2010-01-01"
]

In [20]:
remittances_clean.to_csv(
    r"F:\Mehak Fatima\Pakistan-Economic-Intelligence-Platform\Data\Cleaned Data\remittances_clean.csv",
    index=False
)